// layout.tsx
import type { Metadata } from "next";
import BuyerSidebar from "@/components/BuyerSidebar";
import { IoSettingsOutline, IoShareSocialOutline } from "react-icons/io5";
import ThemeSwitcher from "@/components/ThemeSwithcer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen">
      <BuyerSidebar />
      <main className="flex-1 p-4 pt-0">
        <nav className="flex gap-2 text-sm h-[40px] right-2 fixed">
          <button className="bg-gray-100 w-10 h-14 pb-3 hover:h-16 rounded-b-xl cursor-pointer flex flex-col items-center justify-end transition-all">
            <ThemeSwitcher />
          </button>
          <button className="bg-gray-100 w-10 h-14 pb-3 hover:h-16 rounded-b-xl cursor-pointer flex flex-col items-center justify-end transition-all">
            <IoShareSocialOutline className="text-2xl" />
          </button>
          <button className="bg-gray-100 w-10 h-14 pb-3 hover:h-16 rounded-b-xl cursor-pointer flex flex-col items-center justify-end transition-all">
            <IoSettingsOutline className="text-2xl" />
          </button>
        </nav>
        {children}
      </main>
    </div>
  );
}
